[workspace]
members = ["bpftop", "ebpf-metrics"]
resolver = "2"

[workspace.package]
authors = ["Jose Fernandez <josef@netflix.com>"]
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
